### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by MirceaDumitrescu** [Minebench/HopperImprovements#3] opened 2018-11-29 18:25 UTC
I'm using tacospigot and the moment i started the server, it created a 300mb log file in 3 minutes.

Had to remove it because it was spamming my console with crazy erors. I'll attach the error here, tell me if you need any other info.

`[13:13:52] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to HopperImprovements v1.0-SNAPSHOT (build #20)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.TileEntityHopper.r(TileEntityHopper.java:434) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:193) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:181) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1522) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:603) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:848) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getStorageContents()[Lorg/bukkit/inventory/ItemStack;
	at de.minebench.hopperimprovements.InventoryUtils.atLeastOneFitsInInventory(InventoryUtils.java:41) ~[?:?]
	at de.minebench.hopperimprovements.listeners.InventoryMoveItemListener.onInventoryMoveLow(InventoryMoveItemListener.java:66) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[BeerSpigot.jar:git-TacoSpigot-fd3209f3]
	... 14 more`

**Comment by birkhofflee** [comment] 2019-09-18 09:55
Same here, PaperSpigot 1.8.8

**Comment by Phoenix616** [comment] 2019-09-20 21:31
The plugin is not compatible with 1.8, please use a more modern version (at least 1.9) or PR in a fix if you really care to support such an outdated version.

**Comment by Phoenix616** [comment] 2019-09-20 21:32
Also a duplicate of #1.

**Closed as completed by Phoenix616** 2019-09-20 21:32 UTC
